# Generated by Django 5.1.3 on 2024-11-15 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='meal_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_options_list', to='hostelapp.hostel')),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='meal_options',
            field=models.ManyToManyField(blank=True, related_name='hostels', to='hostelapp.mealoption'),
        ),
    ]
