# Generated by Django 5.1.3 on 2024-11-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0005_meal_remove_hostel_meal_options_booking_meals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='hostelapp.hostel'),
        ),
    ]
