# Generated by Django 5.1.3 on 2024-11-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0007_alter_meal_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='airport_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_guide',
            field=models.BooleanField(default=False),
        ),
    ]
