# Generated by Django 5.1.3 on 2024-11-16 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0008_booking_airport_pickup_booking_tour_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='airport_pickup',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tour_guide',
        ),
        migrations.CreateModel(
            name='AirportPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField()),
                ('flight_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airport_pickup', to='hostelapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='MealService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('served_date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_services', to='hostelapp.booking')),
            ],
        ),
    ]
