# Generated by Django 5.1.3 on 2024-11-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0011_tourguideservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='meals',
        ),
        migrations.AddField(
            model_name='booking',
            name='airport_pickup_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='car_type',
            field=models.CharField(blank=True, choices=[('Taxi', 'Taxi'), ('Van', 'Van')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='include_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='include_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='breakfast_menu',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_menus/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='lunch_menu',
            field=models.ImageField(null=True, upload_to='hostel_menus/'),
        ),
    ]
